# generate_enums_reference.py
"""
Generates docs/EnumsReference.md by scanning src/Bindings/EnumBinding.cpp.

Usage:
    python tools/docs/generate_enums_reference.py
"""

import os
import re
import pathlib

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[2]
ENUM_BINDING_CPP = PROJECT_ROOT / "src" / "Bindings" / "EnumBinding.cpp"
OUTPUT_MD = PROJECT_ROOT / "docs" / "EnumsReference.md"

def parse_enum_bindings():
    if not ENUM_BINDING_CPP.exists():
        print(f"Error: {ENUM_BINDING_CPP} does not exist.")
        return []

    content = ENUM_BINDING_CPP.read_text(encoding="utf-8", errors="ignore")

    ns_pos = content.find("namespace KenshiLua")
    brace_pos = content.find("{", ns_pos)

    reg_pos = content.find("void registerEnumBindings(lua_State* L)")

    body_text = content[brace_pos + 1:reg_pos]

    pattern = r'(\s*//\s*-{5,}\s*\n\s*//\s*[^\n]+\n\s*//\s*-{5,}\s*\n)'
    chunks = re.split(pattern, body_text)

    sections = []

    i = 1
    while i < len(chunks):
        header_block = chunks[i]
        section_code = chunks[i+1] if i+1 < len(chunks) else ""

        lines = [l.strip() for l in header_block.strip().split("\n")]
        header_title = ""
        for line in lines:
            if line.startswith("//") and not line.startswith("// -"):
                header_title = line.lstrip("/ ").strip()
                break

        fn_pattern = r'(void\s+(register\w+)\(lua_State\*\s*L\)\s*\{([^}]+)\})'
        fn_matches = re.findall(fn_pattern, section_code)

        enum_tables = []
        for full_fn, fn_name, fn_body in fn_matches:
            globals_set = re.findall(r'lua_setglobal\(\s*L\s*,\s*"([^"]+)"\s*\);', fn_body)
            nested_set = re.findall(r'setNestedClassTable\(\s*L\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\);', fn_body)
            for parent, field in nested_set:
                globals_set.append(f"{parent}.{field}")

            lines_in_body = fn_body.split("\n")
            set_enum_entries = []

            for line in lines_in_body:
                m = re.search(r'setEnum\(\s*L\s*,\s*"([^"]+)"\s*,\s*([^)]+)\);', line)
                if m:
                    key = m.group(1).strip()
                    val = m.group(2).strip()
                    set_enum_entries.append({
                        "key": key,
                        "val": val
                    })

            enum_tables.append({
                "func_name": fn_name,
                "globals": globals_set,
                "entries": set_enum_entries
            })

        if enum_tables:
            sections.append({
                "header": header_title,
                "enums": enum_tables
            })

        i += 2

    return sections

def generate_markdown(sections):
    md = []
    md.append("# Kenshi LuaJIT Enum Bindings Reference")
    md.append("")
    md.append("This document is automatically generated by `tools/docs/generate_enums_reference.py` based on `src/Bindings/EnumBinding.cpp`.")
    md.append("")
    md.append("## Overview")
    md.append("")
    total_enums = sum(len(s['enums']) for s in sections)
    total_values = sum(len(e['entries']) for s in sections for e in s['enums'])
    md.append(f"Total Enum Registration Functions: **{total_enums}** ({total_values} bound enum values) across **{len(sections)}** SDK header files.")
    md.append("")
    md.append("## Lua Usage & Syntax")
    md.append("")
    md.append("All enums in KenshiLua use their exact literal C++ names and are exposed as global tables or nested class tables (e.g. `CrimeEnum.CRIME_STEALING` or `MeshDataLookup.Dir.FRONT`).")
    md.append("")
    md.append("```lua")
    md.append("-- Accessing enum constants directly:")
    md.append("local prone = ProneState.PS_NORMAL")
    md.append("local crime = CrimeEnum.CRIME_STEALING")
    md.append("local dir   = MeshDataLookup.Dir.FRONT")
    md.append("")
    md.append("-- Passing to a method or setting a property:")
    md.append("character.proneState = ProneState.PS_NORMAL")
    md.append("character:setProneState(ProneState.PS_NORMAL)")
    md.append("```")
    md.append("")
    md.append("### Creating Convenient Local Aliases")
    md.append("")
    md.append("In Lua, you can easily create your own concise aliases at the top of your scripts for readability and convenience:")
    md.append("")
    md.append("```lua")
    md.append("-- Create local aliases for cleaner code:")
    md.append("local Crime = CrimeEnum")
    md.append("local Prone = ProneState")
    md.append("local Dir   = MeshDataLookup.Dir")
    md.append("")
    md.append("if character.crime == Crime.CRIME_STEALING then")
    md.append("    character:setProneState(Prone.PS_NORMAL)")
    md.append("end")
    md.append("```")
    md.append("")
    md.append("## Table of Contents")
    md.append("")
    for sec in sections:
        header_name = sec["header"]
        anchor = header_name.lower().replace(" ", "-").replace("/", "").replace(".", "")
        globals_list = ", ".join([f"`{g}`" for e in sec["enums"] for g in e["globals"]])
        md.append(f"- [{header_name}](#{anchor}) ({globals_list})")

    md.append("")
    md.append("---")
    md.append("")

    for sec in sections:
        header_name = sec["header"]
        anchor = header_name.lower().replace(" ", "-").replace("/", "").replace(".", "")
        md.append(f"## {header_name}")
        md.append("")

        for enum_info in sec["enums"]:
            globals_str = ", ".join([f"`{g}`" for g in enum_info["globals"]]) if enum_info["globals"] else f"`{enum_info['func_name']}`"
            md.append(f"### Table: {globals_str}")
            md.append("")

            def format_lua_syntax(key):
                if enum_info["globals"]:
                    return "<br>".join([f"`{g}.{key}`" for g in enum_info["globals"]])
                return f"`{key}`"

            if enum_info["entries"]:
                md.append("| Lua Syntax | C++ Value / Enumerator |")
                md.append("| :--- | :--- |")
                for entry in enum_info["entries"]:
                    md.append(f"| {format_lua_syntax(entry['key'])} | `{entry['val']}` |")
                md.append("")

        md.append("---")
        md.append("")

    return "\n".join(md)

def main():
    print("Parsing EnumBinding.cpp...")
    sections = parse_enum_bindings()
    print(f"Parsed {len(sections)} header sections.")
    
    markdown_content = generate_markdown(sections)
    
    OUTPUT_MD.write_text(markdown_content, encoding="utf-8")
    print(f"Successfully generated {OUTPUT_MD}")

if __name__ == "__main__":
    main()
