#!/usr/bin/env python3
import os
import re

def main():
    # Paths are relative to the script's grandparent directory (project root)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    bindings_dir = os.path.join(project_root, "src", "Bindings")
    output_file = os.path.join(project_root, "docs", "UnboundRefrence.md")

    unsupported_types = set()
    unsupported_properties = {}
    skipped_methods = []

    # Regex 1: // TODO: Unsupported type for <Field> (<Type>)
    prop_re = re.compile(r'//\s*TODO:\s*Unsupported type for\s+(\w+)\s+\(([^)]+)\)')

    # Regex 2: line <num>: <type> <method>(...) - <reason>
    # e.g., "line 123: int foo(bar) - reason"
    method_re = re.compile(r'^\s*line\s+\d+:\s+([^-(\s]+(?:\s+\w+)?[\*&]?)\s+(\w+)\(.*?\)\s+-\s+(.*)$')

    # Standard types to filter out when checking for unsupported types in skipped methods
    ignored_types_re = re.compile(r'^(void|bool|int|float|double|char|short|long|unsigned|std::string|Ogre::Vector3|Ogre::Quaternion)$')

    # Recursively find and process all .cpp files
    for root, dirs, files in os.walk(bindings_dir):
        for file in files:
            if file.endswith('.cpp'):
                file_path = os.path.join(root, file)
                rel_path = file
                
                try:
                    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                        for line in f:
                            # 1. Search for unsupported properties
                            prop_match = prop_re.search(line)
                            if prop_match:
                                prop = prop_match.group(1)
                                t = prop_match.group(2).strip()
                                unsupported_types.add(t)
                                if t not in unsupported_properties:
                                    unsupported_properties[t] = []
                                unsupported_properties[t].append(f"{rel_path} (Property: {prop})")
                            
                            # 2. Search for skipped methods in comment blocks
                            method_match = method_re.match(line)
                            if method_match:
                                t = method_match.group(1).strip()
                                method = method_match.group(2).strip()
                                reason = method_match.group(3).strip()
                                
                                # Filter out standard types
                                if not ignored_types_re.match(t):
                                    unsupported_types.add(t)
                                
                                skipped_methods.append({
                                    'File': rel_path,
                                    'Type': t,
                                    'Method': method,
                                    'Reason': reason
                                })
                except Exception as e:
                    print(f"Error reading {file_path}: {e}")

    # Generate Markdown Report
    sorted_types = sorted(list(unsupported_types))

    md = []
    md.append("# Unbound Classes and Types Registry")
    md.append("")
    md.append("This document registers all C++ SDK classes and complex types that are currently unsupported, skipped, or fallback-mapped to `lightuserdata` or placeholders within the Lua bindings.")
    md.append("")
    md.append("*(Automatically generated by `dev scripts/generate_list_of_unbound.py`)*")
    md.append("")
    md.append("## Summary of Unique Unbound/Unsupported Types")
    md.append("")
    md.append("| Raw C++ Type | Occurrence Count |")
    md.append("| :--- | :--- |")

    for t in sorted_types:
        # Count occurrences
        count = 0
        if t in unsupported_properties:
            count += len(unsupported_properties[t])
        
        # Count in skipped methods: match t exactly or strip * and &
        stripped_t = t.replace('*', '').replace('&', '')
        for m in skipped_methods:
            m_t = m['Type']
            m_stripped = m_t.replace('*', '').replace('&', '')
            if m_t == t or m_stripped == t:
                count += 1
        
        md.append(f"| `{t}` | {count} |")

    md.append("")
    md.append("## Unsupported Properties Detail")
    md.append("")
    md.append("Below are properties in the bindings files that throw runtime errors due to unsupported types:")
    md.append("")
    md.append("| File | Type | Property Name |")
    md.append("| :--- | :--- | :--- |")

    for t in sorted_types:
        if t in unsupported_properties:
            for prop_occur in unsupported_properties[t]:
                match = re.match(r'^(.+?)\s+\(Property:\s+(.+?)\)$', prop_occur)
                if match:
                    file_name = match.group(1)
                    prop_name = match.group(2)
                    md.append(f"| {file_name} | `{t}` | {prop_name} |")

    md.append("")
    md.append("## Skipped Methods Detail")
    md.append("")
    md.append("Below are methods that were skipped during binding generation:")
    md.append("")
    md.append("| File | Method Name | Type / Return Type | Reason / Issue |")
    md.append("| :--- | :--- | :--- | :--- |")

    # Sort skipped methods by File, then by Method
    sorted_methods = sorted(skipped_methods, key=lambda x: (x['File'], x['Method']))
    for m in sorted_methods:
        md.append(f"| {m['File']} | {m['Method']} | `{m['Type']}` | {m['Reason']} |")

    # Write output file
    try:
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(md) + '\n')
        print(f"Registry successfully written to {output_file}")
    except Exception as e:
        print(f"Error writing output file {output_file}: {e}")

if __name__ == '__main__':
    main()
