-- LuaLS regression fixture: MyGUI factories, inherited widget members, and managers.

local button = MyGUI.createButton("Button", 0, 0, 120, 24)
if button then
    button:setCaption("LuaLS fixture")
    button:setPosition(MyGUI.IntPoint.new(0, 0))
    button:setSize(MyGUI.IntSize.new(120, 24))
    button:setCoord(MyGUI.IntCoord.new(0, 0, 120, 24))
    button:setRealPosition(0.0, 0.0)
    button:setRealSize(0.1, 0.1)
    button:setRealCoord(0.0, 0.0, 0.1, 0.1)
    button:setCoordReal(0.0, 0.0, 0.1, 0.1)
    button:setAlign(MyGUI.Align.Default)
    button:setAlpha(1.0)
    button:setInheritsAlpha(true)
    button:setColour(MyGUI.Colour.new(1, 1, 1, 1))
    button:setDepth(0)
    button:setEnabled(true)
    button:setWidgetStyle(MyGUI.WidgetStyle.Child)
    button:setNeedKeyFocus(true)
    button:setNeedMouseFocus(true)
    button:setInheritsPick(true)
    button:setMaskPick("LuaLS fixture")
    button:setPointer("arrow")
    button:setUserString("fixture", "value")
    assert(button:getUserString("fixture") == "value" and button:isUserString("fixture"))
    button:clearUserString("fixture")
    local positionX, positionY = button:getPosition()
    local width, height = button:getSize()
    local left, top, coordWidth, coordHeight = button:getCoord()
    local realX, realY = button:getRealPosition()
    local realWidth, realHeight = button:getRealSize()
    local realLeft, realTop, realCoordWidth, realCoordHeight = button:getRealCoord()
    local aliasLeft, aliasTop, aliasWidth, aliasHeight = button:getCoordReal()
    assert(positionX + positionY + width + height + left + top + coordWidth + coordHeight >= 0)
    assert(realX + realY + realWidth + realHeight + realLeft + realTop + realCoordWidth + realCoordHeight >= 0)
    assert(aliasLeft + aliasTop + aliasWidth + aliasHeight >= 0)
    assert(button:getInheritedVisible() and button:getInheritedEnabled())
    assert(button:getAlign() == MyGUI.Align.Default and button:getAlpha() == 1.0)
    assert(button:getInheritsAlpha() and button:getDepth() == 0)
    assert(button:getWidgetStyle() == MyGUI.WidgetStyle.Child)
    assert(button:getNeedKeyFocus() and button:getNeedMouseFocus() and button:getInheritsPick())
    assert(type(button:getPointer()) == "string")
    local client = button:getClientWidget()
    if client then
        client:setVisible(true)
    end
    local clientLeft, clientTop, clientWidth, clientHeight = button:getClientCoord()
    local absoluteLeft, absoluteTop, absoluteWidth, absoluteHeight = button:getAbsoluteCoord()
    local absoluteX, absoluteY = button:getAbsolutePosition()
    local rectLeft, rectTop, rectRight, rectBottom = button:getAbsoluteRect()
    assert(clientLeft + clientTop + clientWidth + clientHeight >= 0)
    assert(absoluteLeft + absoluteTop + absoluteWidth + absoluteHeight + absoluteX + absoluteY >= 0)
    assert(rectLeft + rectTop + rectRight + rectBottom >= 0)
    assert(type(button:getLayerName()) == "string" and type(button:isRootWidget()) == "boolean")
    local callbackId = button:on("eventMouseButtonClick", function(sender)
        sender:setVisible(true)
    end)
    button:off(callbackId)
    local compatibilityCallbackId = button:registerCallback("eventMouseButtonClick", function(sender)
        sender:setVisible(true)
    end)
    button:off(compatibilityCallbackId)
    button.alpha = button:getAlpha()
    button.caption = button:getCaption()
    button.text = button.caption
    button.enabled = button:getEnabled()
    button.visible = button:getVisible()
    assert(type(button.name) == "string" and type(button.type) == "string")
    button:setStateSelected(true)
    button:setModeImage(true)
    button:setImageResource("LuaLS fixture")
    button.selected = button:getStateSelected()
end

local progress = MyGUI.createProgressBar("ProgressBar", 0, 30, 120, 24)
if progress then
    progress:setProgressRange(100)
    progress:setProgressPosition(25)
    progress:setProgressAutoTrack(true)
    progress:setFlowDirection(MyGUI.FlowDirection.LeftToRight)
    progress.range = progress:getProgressRange()
    progress.position = progress:getProgressPosition()
end

local window = MyGUI.createWindow("Window", 0, 60, 320, 200)
if window then
    window:setAutoAlpha(true)
    window:setSnap(true)
    window:setMovable(true)
    window:setMinSize(MyGUI.IntSize.new(100, 80))
    window:setMaxSize(800, 600)
    local minWidth, minHeight = window:getMinSize()
    local maxWidth, maxHeight = window:getMaxSize()
    assert(minWidth <= maxWidth and minHeight <= maxHeight)
    local actionScale = window:getActionScale()
    local caption = window:getCaptionWidget()
    window.autoAlpha = actionScale ~= nil
    window.snap = caption ~= nil
    window.movable = window:getMovable()
end

local dragContainer = MyGUI.createDDContainer("DDContainer", 0, 270, 120, 80)
if dragContainer then
    dragContainer:setNeedDragDrop(true)
    assert(dragContainer:getNeedDragDrop())
    dragContainer:resetDrag()
end

local image = MyGUI.createImageBox("ImageBox", 130, 270, 120, 80)
if image then
    image:setImageTexture("LuaLS fixture")
    image:setImageCoord(MyGUI.IntCoord.new(0, 0, 32, 32))
    image:setImageTile(16, 16)
    image:setImageIndex(0)
    image:setItemSelect(image:getImageIndex())
    local itemCount = image:getItemCount()
    local selectedItem = image:getItemSelect()
    assert(itemCount >= 0 and selectedItem >= 0)
    image:resetItemSelect()
    image:setImageResource("LuaLS fixture")
end

local scrollView = MyGUI.createScrollView("ScrollView", 260, 270, 180, 120)
if scrollView then
    scrollView:setVisibleHScroll(true)
    scrollView:setVisibleVScroll(true)
    assert(scrollView:isVisibleHScroll() and scrollView:isVisibleVScroll())
    scrollView:setCanvasAlign(MyGUI.Align.Default)
    scrollView:setCanvasSize(MyGUI.IntSize.new(320, 240))
    scrollView:setViewOffset(10, 20)
    local canvasWidth, canvasHeight = scrollView:getCanvasSize()
    local offsetX, offsetY = scrollView:getViewOffset()
    local viewLeft, viewTop, viewWidth, viewHeight = scrollView:getViewCoord()
    assert(canvasWidth + canvasHeight + offsetX + offsetY >= 0)
    assert(viewLeft + viewTop + viewWidth + viewHeight >= 0)
end

local textBox = MyGUI.createTextBox("TextBox", 0, 400, 180, 40)
if textBox then
    textBox:setFontName("Default")
    textBox:setFontHeight(16)
    textBox:setTextAlign(MyGUI.Align.Left)
    textBox:setTextColour(MyGUI.Colour.new(1, 1, 1, 1))
    textBox:setCaptionWithReplacing("LuaLS fixture")
    textBox.fontName = textBox:getFontName()
    textBox.fontHeight = textBox:getFontHeight()
    local textLeft, textTop, textWidth, textHeight = textBox:getTextRegion()
    local measuredWidth, measuredHeight = textBox:getTextSize()
    local textColour = textBox:getTextColour()
    assert(textLeft + textTop + textWidth + textHeight >= 0)
    assert(measuredWidth + measuredHeight >= 0 and textColour ~= nil)
end

local itemBox = MyGUI.createItemBox("ItemBox", 190, 400, 180, 100)
if itemBox then
    itemBox:addItem()
    itemBox:insertItemAt(0)
    itemBox:setIndexSelected(0)
    local selectedIndex = itemBox:getIndexSelected()
    local itemWidget = itemBox:getWidgetByIndex(0)
    if itemWidget then
        assert(itemBox:getIndexByWidget(itemWidget) >= 0)
    end
    local dragWidget = itemBox:getWidgetDrag()
    if dragWidget then
        dragWidget:setVisible(true)
    end
    itemBox:redrawItemAt(0)
    itemBox:redrawAllItems()
    itemBox:clearIndexSelected()
    itemBox:removeItemAt(0)
    assert(selectedIndex >= -1 and itemBox:getItemCount() >= 0)
    itemBox:removeAllItems()
end

local canvas = MyGUI.createCanvas("Canvas", 380, 400, 180, 100)
if canvas then
    canvas:createTexture(128, 128)
    canvas:setTextureManaged(true)
    canvas:updateTexture()
    assert(canvas:isTextureCreated() and canvas:isTextureManaged())
    local realWidth, realHeight = canvas:getTextureRealSize()
    local sourceWidth, sourceHeight = canvas:getTextureSrcSize()
    local sourceSized = canvas:isTextureSrcSize()
    assert(realWidth == canvas:getTextureRealWidth())
    assert(realHeight == canvas:getTextureRealHeight())
    assert(sourceWidth == canvas:getTextureSrcWidth())
    assert(sourceHeight == canvas:getTextureSrcHeight())
    local textureName = canvas:getTextureName()
    local textureFormat = canvas:getTextureFormat()
    canvas:setResizeMode(canvas:getResizeMode())
    assert(type(textureName) == "string" and textureFormat >= 0 and type(sourceSized) == "boolean")
    canvas:destroyTexture()
end

local listBox = MyGUI.createListBox("ListBox", 0, 510, 180, 120)
if listBox then
    listBox:addItem("first")
    listBox:insertItemAt(0, "inserted")
    listBox:setItemNameAt(0, "renamed")
    listBox:swapItemsAt(0, 1)
    listBox:setIndexSelected(0)
    listBox.indexSelected = listBox:getIndexSelected()
    listBox.selectedIndex = listBox.indexSelected
    listBox:beginToItemAt(0)
    listBox:beginToItemFirst()
    listBox:beginToItemLast()
    listBox:beginToItemSelected()
    listBox:setScrollVisible(true)
    listBox:setScrollPosition(0)
    local listWidget = listBox:getWidgetByIndex(0)
    local visible = listBox:isItemVisibleAt(0, true)
    local selectedVisible = listBox:isItemSelectedVisible()
    assert(listBox:getItemNameAt(0) == "renamed")
    assert(listBox:findItemIndexWith("renamed") >= -1)
    assert(listBox.itemCount == listBox.count and listBox:getItemCount() >= 0)
    assert(listBox:getOptimalHeight() >= 0 and type(visible) == "boolean")
    assert(type(selectedVisible) == "boolean" and (listWidget == nil or listWidget:getVisible()))
    listBox:clearIndexSelected()
    listBox:removeItemAt(0)
    listBox:removeAllItems()
end

local comboBox = MyGUI.createComboBox("ComboBox", 190, 510, 180, 30)
if comboBox then
    comboBox:addItem("first")
    comboBox:insertItemAt(0, "inserted")
    comboBox:setItemNameAt(0, "renamed")
    comboBox:setIndexSelected(0)
    comboBox.indexSelected = comboBox:getIndexSelected()
    comboBox.selectedIndex = comboBox.indexSelected
    comboBox:setComboModeDrop(true)
    comboBox.comboModeDrop = comboBox:getComboModeDrop()
    comboBox.modeDrop = comboBox.comboModeDrop
    comboBox:setSmoothShow(true)
    comboBox:setMaxListLength(10)
    comboBox:setFlowDirection(MyGUI.FlowDirection.TopToBottom)
    comboBox:beginToItemAt(0)
    comboBox:beginToItemFirst()
    comboBox:beginToItemLast()
    comboBox:beginToItemSelected()
    assert(comboBox:getItemNameAt(0) == "renamed")
    assert(comboBox:findItemIndexWith("renamed") >= -1)
    assert(comboBox.itemCount == comboBox.count and comboBox:getItemCount() >= 0)
    assert(comboBox:getSmoothShow() and comboBox:getMaxListLength() == 10)
    assert(comboBox:getFlowDirection() == MyGUI.FlowDirection.TopToBottom)
    comboBox:clearIndexSelected()
    comboBox:removeItemAt(0)
    comboBox:removeAllItems()
end

local tabControl = MyGUI.createTabControl("TabControl", 380, 510, 240, 140)
if tabControl then
    local firstTab = tabControl:addItem("first")
    local insertedTab = tabControl:insertItemAt(0, "inserted")
    if firstTab then
        firstTab:setButtonWidth(80)
    end
    if insertedTab then
        insertedTab:setButtonWidth(90)
    end
    tabControl:setItemNameAt(0, "renamed")
    tabControl:setIndexSelected(0)
    tabControl.indexSelected = tabControl:getIndexSelected()
    tabControl.selectedIndex = tabControl.indexSelected
    tabControl:setButtonWidthAt(0, 90)
    tabControl:setButtonDefaultWidth(80)
    tabControl:setButtonAutoWidth(true)
    tabControl:setSmoothShow(true)
    local tabAt = tabControl:getItemAt(0)
    local selectedTab = tabControl:getItemSelected()
    assert(tabControl:getItemNameAt(0) == "renamed")
    assert(tabControl:getButtonWidthAt(0) >= 0)
    assert(tabControl:getButtonDefaultWidth() >= 0 and tabControl:getButtonAutoWidth())
    assert(tabControl:getSmoothShow() and tabControl.itemCount == tabControl.count)
    assert(tabAt ~= nil and selectedTab ~= nil)
    tabControl:clearIndexSelected()
    tabControl:removeItemAt(0)
    tabControl:removeAllItems()
end

local scrollBar = MyGUI.createScrollBar("ScrollBar", 630, 510, 20, 140)
if scrollBar then
    scrollBar:setScrollRange(100)
    scrollBar:setScrollPosition(25)
    scrollBar.scrollPosition = scrollBar:getScrollPosition()
    scrollBar.position = scrollBar.scrollPosition
    scrollBar.scrollRange = scrollBar:getScrollRange()
    scrollBar.range = scrollBar.scrollRange
    scrollBar:setScrollPage(10)
    scrollBar:setScrollViewPage(20)
    scrollBar:setScrollWheelPage(5)
    scrollBar:setVerticalAlignment(true)
    scrollBar:setTrackSize(16)
    scrollBar:setMinTrackSize(8)
    scrollBar:setMoveToClick(true)
    scrollBar:setRepeatEnabled(true)
    assert(scrollBar:getScrollPage() == 10)
    assert(scrollBar:getScrollViewPage() == 20 and scrollBar:getScrollWheelPage() == 5)
    assert(scrollBar:getVerticalAlignment() and scrollBar:getLineSize() >= 0)
    assert(scrollBar:getTrackSize() == 16 and scrollBar:getMinTrackSize() == 8)
    assert(scrollBar:getMoveToClick() and scrollBar:getRepeatEnabled())
end

local menu = MyGUI.createMenuBar("MenuBar", 0, 660, 300, 30)
if menu then
    local fileItem = menu:addItem("File", MyGUI.MenuItemType.Popup, "file")
    local editItem = menu:insertItemAt(0, "Edit", MyGUI.MenuItemType.Normal, "edit")
    menu:setItemNameAt(0, "Edit menu")
    menu:setItemIdAt(0, "edit-menu")
    menu:setItemDataAt(0, "fixture data")
    menu:setItemTypeAt(0, MyGUI.MenuItemType.Normal)
    menu:setItemChildVisibleAt(0, true)
    menu:setPopupAccept(true)
    menu:setPopupMode(menu:getPopupAccept())
    menu:setVerticalAlignment(false)
    local childMenu = menu:createItemChildAt(0)
    local itemAt = menu:getItemAt(0)
    local itemById = menu:getItemById("edit-menu")
    if fileItem then
        fileItem:setItemName("File menu")
        fileItem.itemName = fileItem:getItemName()
        fileItem:setItemId("file-menu")
        fileItem.itemId = fileItem:getItemId()
        fileItem:setItemType(MyGUI.MenuItemType.Popup)
        fileItem:setItemData("fixture data")
        fileItem:setItemChecked(true)
        fileItem.checked = fileItem:getItemChecked()
        fileItem:setItemChildVisible(true)
        local fileChild = fileItem:createItemChild()
        local existingChild = fileItem:getItemChild()
        assert(fileItem:getItemIndex() >= -1 and fileItem:getItemType() == MyGUI.MenuItemType.Popup)
        assert(fileChild ~= nil or existingChild ~= nil)
        fileItem:clearItemData()
        fileItem:removeItemChild()
    end
    assert(editItem ~= nil and childMenu ~= nil and itemAt ~= nil and itemById ~= nil)
    assert(menu:getItemNameAt(0) == "Edit menu" and menu:getItemIdAt(0) == "edit-menu")
    assert(menu:getItemIndex(itemAt) >= 0 and menu:getItemIndexById("edit-menu") >= 0)
    assert(menu:findItemIndexWith("Edit menu") >= 0)
    assert(menu:getItemTypeAt(0) == MyGUI.MenuItemType.Normal)
    assert(menu:getPopupMode() and not menu:getVerticalAlignment())
    menu:clearItemDataAt(0)
    menu:removeItemAt(0)
    menu:removeAllItems()
end

local multiList = MyGUI.createMultiListBox("MultiListBox", 310, 660, 320, 160)
if multiList then
    multiList:addColumn("Name", 160)
    multiList:insertColumnAt(0, "ID", 80)
    multiList:setColumnNameAt(0, "Identifier")
    multiList:setColumnWidthAt(0, 100)
    multiList:addItem("first")
    multiList:insertItemAt(0, "inserted")
    multiList:setItemNameAt(0, "renamed")
    multiList:swapItemsAt(0, 1)
    multiList:setSubItemNameAt(1, 0, "detail")
    multiList:setIndexSelected(0)
    multiList.indexSelected = multiList:getIndexSelected()
    multiList.selectedIndex = multiList.indexSelected
    assert(multiList:getColumnNameAt(0) == "Identifier")
    assert(multiList:getColumnWidthAt(0) == 100 and multiList:getColumnCount() >= 0)
    assert(multiList:getItemNameAt(0) == "renamed" and multiList:getItemCount() >= 0)
    assert(multiList:getSubItemNameAt(1, 0) == "detail")
    assert(multiList:findSubItemWith(1, "detail") >= -1)
    assert(multiList.itemCount == multiList.count and multiList.columnCount >= 0)
    multiList:clearIndexSelected()
    multiList:removeItemAt(0)
    multiList:removeAllItems()
    multiList:removeColumnAt(0)
    multiList:removeAllColumns()
end

local editBox = MyGUI.createEditBox("EditBox", 0, 830, 300, 80)
if editBox then
    editBox:setOnlyText("LuaLS fixture text")
    editBox:addText(" appended")
    editBox:insertText("prefix ", 0)
    editBox:eraseText(0, 1)
    editBox:setTextCursor(2)
    editBox:setTextSelection(0, 5)
    editBox:setTextIntervalColour(0, 5, MyGUI.Colour.new(1, 1, 0, 1))
    editBox:setTextSelectionColour(MyGUI.Colour.new(0, 1, 1, 1))
    editBox:setOverflowToTheLeft(false)
    editBox:setMaxTextLength(200)
    editBox:setEditWordWrap(true)
    editBox:setEditReadOnly(false)
    editBox:setEditMultiLine(true)
    editBox:setEditPassword(false)
    editBox:setEditStatic(false)
    editBox:setPasswordChar("*")
    editBox.readOnly = editBox:getEditReadOnly()
    editBox.multiLine = editBox:getEditMultiLine()
    editBox.wordWrap = editBox:getEditWordWrap()
    local selection = editBox:getTextSelection()
    local selectionStart = editBox:getTextSelectionStart()
    local selectionEnd = editBox:getTextSelectionEnd()
    local selectionLength = editBox:getTextSelectionLength()
    local interval = editBox:getTextInterval(0, 5)
    assert(type(selection) == "string" and type(interval) == "string")
    assert(selectionStart + selectionEnd + selectionLength >= 0)
    assert(editBox:getTextCursor() >= 0 and editBox:getTextLength() >= 0)
    assert(not editBox:getOverflowToTheLeft() and editBox:getMaxTextLength() == 200)
    assert(editBox:getEditWordWrap() and editBox:getEditMultiLine())
    assert(not editBox:getEditPassword() and not editBox:getEditStatic())
    assert(editBox:getPasswordChar() == "*" and type(editBox:getOnlyText()) == "string")
    assert(type(editBox:isTextSelection()) == "boolean")
    editBox:deleteTextSelection()
end

local input = MyGUI.InputManager.getInstance()
if input then
    local mouseX, mouseY = input:getMousePosition()
    input:injectMouseMove(mouseX, mouseY)
end

local point = IntPoint.new(10, 20)
assert(point.x == 10 and point.y == 20)
