# generate_enum_reference.py
"""
Generates docs/EnumsReference.md by scanning src/Bindings/EnumBinding.cpp.

Usage:
    python tools/generate_enum_reference.py
"""

import os
import re
import pathlib

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
ENUM_BINDING_CPP = PROJECT_ROOT / "src" / "Bindings" / "EnumBinding.cpp"
OUTPUT_MD = PROJECT_ROOT / "docs" / "EnumsReference.md"

def parse_enum_bindings():
    if not ENUM_BINDING_CPP.exists():
        print(f"Error: {ENUM_BINDING_CPP} does not exist.")
        return []

    content = ENUM_BINDING_CPP.read_text(encoding="utf-8", errors="ignore")

    ns_pos = content.find("namespace KenshiLua")
    brace_pos = content.find("{", ns_pos)

    reg_pos = content.find("void registerEnumBindings(lua_State* L)")

    body_text = content[brace_pos + 1:reg_pos]

    pattern = r'(\s*//\s*-{5,}\s*\n\s*//\s*[^\n]+\n\s*//\s*-{5,}\s*\n)'
    chunks = re.split(pattern, body_text)

    sections = []

    i = 1
    while i < len(chunks):
        header_block = chunks[i]
        section_code = chunks[i+1] if i+1 < len(chunks) else ""

        lines = [l.strip() for l in header_block.strip().split("\n")]
        header_title = ""
        for line in lines:
            if line.startswith("//") and not line.startswith("// -"):
                header_title = line.lstrip("/ ").strip()
                break

        fn_pattern = r'(void\s+(register\w+)\(lua_State\*\s*L\)\s*\{([^}]+)\})'
        fn_matches = re.findall(fn_pattern, section_code)

        enum_tables = []
        for full_fn, fn_name, fn_body in fn_matches:
            globals_set = re.findall(r'lua_setglobal\(\s*L\s*,\s*"([^"]+)"\s*\);', fn_body)

            lines_in_body = fn_body.split("\n")
            current_category = "Original"

            set_enum_entries = []
            seen_cpp_vals = set()

            for line in lines_in_body:
                l = line.strip()
                if l.startswith("//") and "alias" in l.lower():
                    current_category = "Alias"
                elif l.startswith("//") and "original" in l.lower():
                    current_category = "Original"

                m = re.search(r'setEnum\(\s*L\s*,\s*"([^"]+)"\s*,\s*([^)]+)\);', line)
                if m:
                    key = m.group(1).strip()
                    val = m.group(2).strip()

                    cat = current_category
                    if val in seen_cpp_vals and cat != "Alias":
                        cat = "Alias"
                    seen_cpp_vals.add(val)

                    set_enum_entries.append({
                        "key": key,
                        "val": val,
                        "category": cat
                    })

            enum_tables.append({
                "func_name": fn_name,
                "globals": globals_set,
                "entries": set_enum_entries
            })

        if enum_tables:
            sections.append({
                "header": header_title,
                "enums": enum_tables
            })

        i += 2

    return sections

def generate_markdown(sections):
    md = []
    md.append("# Kenshi LuaJIT Enum Bindings Reference")
    md.append("")
    md.append("This document is automatically generated by `tools/generate_enum_reference.py` based on `src/Bindings/EnumBinding.cpp`.")
    md.append("")
    md.append("## Overview")
    md.append("")
    total_enums = sum(len(s['enums']) for s in sections)
    total_values = sum(len(e['entries']) for s in sections for e in s['enums'])
    md.append(f"Total Enum Registration Functions: **{total_enums}** ({total_values} bound values/aliases) across **{len(sections)}** SDK header files.")
    md.append("")
    md.append("## Table of Contents")
    md.append("")
    for sec in sections:
        header_name = sec["header"]
        anchor = header_name.lower().replace(" ", "-").replace("/", "").replace(".", "")
        globals_list = ", ".join([f"`{g}`" for e in sec["enums"] for g in e["globals"]])
        md.append(f"- [{header_name}](#{anchor}) ({globals_list})")

    md.append("")
    md.append("---")
    md.append("")

    for sec in sections:
        header_name = sec["header"]
        anchor = header_name.lower().replace(" ", "-").replace("/", "").replace(".", "")
        md.append(f"## {header_name}")
        md.append("")

        for enum_info in sec["enums"]:
            globals_str = ", ".join([f"`{g}`" for g in enum_info["globals"]]) if enum_info["globals"] else f"`{enum_info['func_name']}`"
            md.append(f"### Global: {globals_str}")
            md.append("")
            md.append(f"C++ Binding Function: `{enum_info['func_name']}(lua_State* L)`")
            md.append("")

            originals = [e for e in enum_info["entries"] if e["category"] == "Original"]
            aliases = [e for e in enum_info["entries"] if e["category"] == "Alias"]

            if originals:
                if aliases:
                    md.append("**Original Enumerators:**")
                    md.append("")
                md.append("| Lua Key / Name | C++ Value / Enumerator |")
                md.append("| :--- | :--- |")
                for entry in originals:
                    md.append(f"| `{entry['key']}` | `{entry['val']}` |")
                md.append("")

            if aliases:
                md.append("**Aliases:**")
                md.append("")
                md.append("| Lua Key / Name | C++ Value / Enumerator |")
                md.append("| :--- | :--- |")
                for entry in aliases:
                    md.append(f"| `{entry['key']}` | `{entry['val']}` |")
                md.append("")

        md.append("---")
        md.append("")

    return "\n".join(md)

def main():
    print("Parsing EnumBinding.cpp...")
    sections = parse_enum_bindings()
    print(f"Parsed {len(sections)} header sections.")
    
    markdown_content = generate_markdown(sections)
    
    OUTPUT_MD.write_text(markdown_content, encoding="utf-8")
    print(f"Successfully generated {OUTPUT_MD}")

if __name__ == "__main__":
    main()
