# generate_callbacks_reference.py
"""
Generates docs/CallbacksReference.md by scanning src/Callbacks.h and src/Hooks.cpp.

Usage:
    python tools/generate_callbacks_reference.py
"""

import os
import re
import pathlib

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
CALLBACKS_HEADER = PROJECT_ROOT / "src" / "Callbacks.h"
HOOKS_CPP = PROJECT_ROOT / "src" / "Hooks.cpp"
OUTPUT_MD = PROJECT_ROOT / "docs" / "CallbacksReference.md"

def parse_hooks_registry():
    """Extract eventName -> installer map from g_eventHookRegistry in Hooks.cpp."""
    event_map = {}
    if not HOOKS_CPP.exists():
        return event_map

    content = HOOKS_CPP.read_text(encoding="utf-8", errors="ignore")
    match = re.search(r"g_eventHookRegistry\[\]\s*=\s*\{([^\}]+)\};", content, re.DOTALL)
    if match:
        body = match.group(1)
        entries = re.findall(r'\{\s*"([^"]+)"\s*,\s*([^\s,\}]+)\s*\}', body)
        for event_name, installer in entries:
            event_map[event_name] = installer
    return event_map

def parse_callbacks_header():
    """Parse src/Callbacks.h for callback dispatcher functions and their comment metadata."""
    if not CALLBACKS_HEADER.exists():
        return []

    content = CALLBACKS_HEADER.read_text(encoding="utf-8", errors="ignore")
    lines = content.splitlines()

    callbacks = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        
        # Look for dispatcher function declaration
        if line.endswith(';') and ('Call' in line) and ('Callbacks(' in line):
            # Parse function signature
            func_sig = line
            
            # Extract return type and function name
            match = re.match(r"^([\w<>:\*\&\s]+?)\s+(Call\w+Callbacks)\s*\((.*)\);$", func_sig)
            if match:
                ret_type = match.group(1).strip()
                func_name = match.group(2).strip()
                params = match.group(3).strip()

                # Gather preceding comments
                comments = []
                j = i - 1
                while j >= 0 and lines[j].strip().startswith('//'):
                    comments.insert(0, lines[j].strip()[2:].strip())
                    j -= 1

                fired_by = ""
                lua_event = ""
                lua_sig = ""
                extra_notes = []

                for c in comments:
                    if c.startswith("Fired by"):
                        fired_by = c.replace("Fired by", "").strip().rstrip('.')
                    elif c.startswith("Lua event name:"):
                        ev = c.replace("Lua event name:", "").strip().strip('"')
                        if ev:
                            lua_event = ev
                    elif c.startswith("Lua signature:"):
                        lua_sig = c.replace("Lua signature:", "").strip()
                    else:
                        extra_notes.append(c)

                callbacks.append({
                    'func_name': func_name,
                    'ret_type': ret_type,
                    'params': params,
                    'fired_by': fired_by,
                    'lua_event': lua_event,
                    'lua_sig': lua_sig,
                    'notes': " ".join(extra_notes).strip()
                })
        i += 1

    return callbacks

def generate_markdown(callbacks, registry_map):
    output = []
    output.append("# Kenshi LuaJIT Callbacks Reference")
    output.append("")
    output.append("This document is automatically generated by `tools/generate_callbacks_reference.py` based on `src/Callbacks.h` and `src/Hooks.cpp`.")
    output.append("")
    output.append("## Overview")
    output.append("")
    output.append("KenshiLuaJIT provides an event-driven callback system allowing Lua scripts to subscribe to in-game events using `registerHandler` and `unregisterHandler` globals.")
    output.append("")
    output.append("```lua")
    output.append("-- Registering an event handler")
    output.append("local handlerId = registerHandler(\"onCharacterDeath\", function(character)")
    output.append("    print(\"Character died: \", character)")
    output.append("end)")
    output.append("")
    output.append("-- Unregistering when done")
    output.append("unregisterHandler(handlerId)")
    output.append("```")
    output.append("")
    output.append("### Two Types of Callbacks")
    output.append("")
    output.append("1. **Notification Callbacks (Observer Pattern)**: Fired when an event occurs in the game. Handlers observe the event with typed arguments. Returning `false` from a handler suppresses execution of subsequent Lua handlers for that event, but does not interrupt C++ engine logic.")
    output.append("2. **Override Callbacks (Interceptor Pattern)**: Fired when the engine queries a value or object pointer (e.g. food selection, stat calculation, building availability). Handlers receive arguments (and default values). If a handler returns a non-nil value matching the expected return type, the C++ hook uses the returned value to override the engine's original calculation.")
    output.append("")

    # Split into Notifications and Overrides
    notifications = []
    overrides = []

    for cb in callbacks:
        is_override = cb['ret_type'] != 'void'
        if is_override:
            overrides.append(cb)
        else:
            notifications.append(cb)

    output.append(f"## 1. Notification Callbacks ({len(notifications)})")
    output.append("")
    output.append("| Event Name | Source Engine Hook | Lua Signature | Dispatcher Function |")
    output.append("| :--- | :--- | :--- | :--- |")
    for cb in notifications:
        ev_name = f"`{cb['lua_event']}`" if cb['lua_event'] else "*(Unmapped)*"
        fired = f"`{cb['fired_by']}`" if cb['fired_by'] else "*(Engine Hook)*"
        sig = f"`{cb['lua_sig']}`" if cb['lua_sig'] else "`function(...)`"
        func = f"`{cb['func_name']}`"
        output.append(f"| {ev_name} | {fired} | {sig} | {func} |")
    output.append("")

    output.append(f"## 2. Override Callbacks ({len(overrides)})")
    output.append("")
    output.append("| Event Name | Source Engine Hook | Lua Signature & Expected Return | Dispatcher Function |")
    output.append("| :--- | :--- | :--- | :--- |")
    for cb in overrides:
        ev_name = f"`{cb['lua_event']}`" if cb['lua_event'] else "*(Unmapped)*"
        fired = f"`{cb['fired_by']}`" if cb['fired_by'] else "*(Engine Hook)*"
        sig = f"`{cb['lua_sig']}`" if cb['lua_sig'] else f"`function(...) -> {cb['ret_type']}`"
        func = f"`{cb['func_name']}`"
        output.append(f"| {ev_name} | {fired} | {sig} | {func} |")
    output.append("")

    output.append("## Detailed Callback Documentation")
    output.append("")

    all_cbs = notifications + overrides
    all_cbs.sort(key=lambda x: x['lua_event'] or x['func_name'])

    for cb in all_cbs:
        ev_title = cb['lua_event'] if cb['lua_event'] else cb['func_name']
        output.append(f"### `{ev_title}`")
        output.append("")
        output.append(f"- **Category**: {'Override / Interceptor' if cb['ret_type'] != 'void' else 'Notification / Observer'}")
        if cb['fired_by']:
            output.append(f"- **Engine Hook**: `{cb['fired_by']}`")
        output.append(f"- **C++ Dispatcher**: `{cb['ret_type']} {cb['func_name']}({cb['params']})`")
        if cb['lua_sig']:
            output.append(f"- **Lua Signature**: `{cb['lua_sig']}`")
        if cb['notes']:
            output.append(f"- **Notes**: {cb['notes']}")
        output.append("")

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text("\n".join(output), encoding="utf-8")
    print(f"Successfully generated {OUTPUT_MD} with {len(callbacks)} callbacks.")

def main():
    registry_map = parse_hooks_registry()
    callbacks = parse_callbacks_header()
    generate_markdown(callbacks, registry_map)

if __name__ == "__main__":
    main()
